### ISSUE TITLE
Documentation and Changelog are missing

### ISSUE THREAD

**Issue by josch1710** [komh/kai#2]
It looks like there are many changes between 1.1.14 and 1.2.0.
But what are they. Please, at least provide a minimal Changelog and API documentation, so that we can use your amazing library.
Also, it would be helpful, if you could provide some demo code.
If you need help, I will gladly help.

**Comment by komh** [comment]
Thanks for your concern and report.

However, all that you are saying were already provided.

See libkai-1.2.0.txt for minimal changelog.
See include/kai.h for API documentation.
See kaidemo.c and kaidemo2.c in src.zip

**Comment by josch1710** [comment]
kai.h is minimal, indeed ;-)
Where is libkai-1.2.0.txt in this repository? It only seems to be on Hobbes.
Yes, I know the two demos. I didn't specify correctly what I meant, was a demo of the new features.
But reading the libkai-1.2.0.txt, I now realize, you did exactly that ;-)

**Comment by komh** [comment]
Yes, libkai-1.2.0.txt is on Hobbes only. I'll add it later.

Thanks.
